config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  #override the admin devise controller to ours
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }

  get 'admin', to: 'admin/dashboard#index'

  # namespace all admin resources
  namespace :admin do
    resources :users, :designs, :comments, :spots
  end

  # override the user devise controller to ours
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations'
  }

  get 'projetos', to: 'dynamic_pages#projetos'
  get 'individuais/minhas-imagens', to: 'dynamic_pages#individuais', as: :individuais
  get 'individuais/onde-comentei', to: 'dynamic_pages#my_comments', as: :my_comments
  post 'create_single', to: 'singles#create', as: :create_single

  # resources :users

  match 'contato', to: 'static_pages#contact', via: [:get, :post], as: :contact

  match 'a/create_comment', to: 'comments#create', via: [:post], as: :create_design_comment
  match 'a/delete_comment/:comment_id', to: 'comments#delete', via: [:delete], as: :delete_design_comment
  match 'a/delete_spot/:spot_id', to: 'spots#delete', via: [:delete], as: :delete_design_spot
  match 'delete_design/:design_id', to: 'singles#delete', via: [:delete], as: :delete_design

  match 'a/update_title', to: 'singles#update_title', via: [:patch], as: :update_design_title
  match 'a/update_subtitle', to: 'singles#update_subtitle', via: [:patch], as: :update_design_subtitle
  match 'a/feedback_app', to: 'singles#feedback_app', via: [:get], as: :feedback_app

  match ':design_link', to: 'singles#show', via: [:get], as: :design

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :spot
  belongs_to :design
  belongs_to :user

  validates :comment,
    presence: { message: 'O comentário é necessário.'},
    length: { maximum: 250, message: 'Seu comentário deve possuir no máximo 200 caracteres.' }
  validates :user, presence: { message: 'Voce precisa estar logado para comentar.'}
  validates :spot, presence: { message: 'Um Spot precisa estar associado a este comentário' }
  validates :design, presence: { message: 'Um Design precisa estar associado a este comentário' }

  before_save :strip_columns, :nullify_fields

  # check if user can delete a comment
  # author: rffaguiar
  # since: 1.0
  # date: 25/03
  def can_user_delete?(current_user = nil)
    return false if current_user.nil?


    if current_user.id == self.user.id
      # can delete - comment owner
      return true
    # this decision is up to you: to enable the design owner delete the comment
    # elsif current_user.id == self.design.user.id
    #   # can delete - design owner
    #   return true
    elsif current_user.id != self.user.id
      # 'cannot delete - user is logged, but isnt comment owner'
      return false
    else
      # can't delete - guest
      return false
    end
  end

  private

    # normalization: nil to fields and they respond true to empty?
    # author: rffaguiar
    # since: 1.0
    # date: 16/03/2015
    def nullify_fields
      user_fields = %W(
        comment
      )
      user_fields.each do |field|
        next if self[field].nil?
        self[field] = nil if self[field].empty?
      end
    end

    # normalization: remove whitespace from left and right from all listed fields
    # author: rffaguiar
    # since: 1.0
    # date: 16/03/2015
    def strip_columns
      user_fields = %W(
        comment
      )

      user_fields.each do |field|
        next if self[field].nil?
        self[field] = self[field].strip
      end
    end

end

app/controllers/admin/comments_controller.rb
class Admin::CommentsController < ApplicationController
  layout 'admin'
  before_action :authenticate_admin!

  def index
    @comments = Comment.order(id: :desc).page(params[:page]).per(10)
  end

  def show
    @comment = Comment.find(params[:id])
  end

  def new
  end

  def edit
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])

    if @comment.update(comment_params)
      flash[:notice] = 'Comentário atualizado com sucesso'
      redirect_to admin_comments_path
    else
      render 'edit'
    end
  end

  def destroy
    if Comment.exists?(params[:id])
      @comment = Comment.find(params[:id])
      @spot = @comment.spot
      # verify if this is the last comment
      if @spot.comments.count <= 1
        flash[:notice] = 'Comentário e seu Spot deletado com sucesso'
        @spot.destroy
      else
        flash[:notice] = 'Comentário deletado com sucesso'
        @comment.destroy
      end
    else
      p 'comentário não existe'
    end
    redirect_to admin_comments_path
  end

  private
    def comment_params
      params.require(:comment).permit(:comment)
    end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

    before_action :authenticate_user!, only: [:create, :delete]
    before_action :allowed_user, only: [:delete]

    # Ajax
    # Create a comment in a design. If the spot doesnt exist, a spot and a comment is created. If the spot exists, the comment is created for this spot
    def create

      # params['spot-id'] is not necessary
      # params['design-y-pos'] and params['design-x-pos'] are necessary only if params['spot-id'] is absent

      spot_id = params['spot-id']
      design_id = params['design-id']
      design_comment = params['design-comment-text']

      head :unprocessable_entity and return if design_id.blank? || design_comment.blank?

      if spot_id.present?
        # p 'creating a comment in an existing spot'
        exist_spot = true
        new_spot = false

        @spot = Spot.find(spot_id)
        @comment = @spot.comments.build comment: design_comment, design_id: design_id, user_id: current_user.id
      else
        # p 'creating a comment AND a spot'
        exist_spot = false
        new_spot = true
        @spot = Spot.new x_pos: params['design-x-pos'], y_pos: params['design-y-pos'], design_id: design_id, user_id: current_user.id
        if @spot.valid?
          error_spot = false
          @comment = @spot.comments.build comment: design_comment, design_id: design_id, user_id: current_user.id
        else
          # p @spot.errors
          error_spot = true
        end
      end

      respond_to do |format|
        if error_spot
          format.js { head :unprocessable_entity and return }
          format.html { redirect_to root_path, notice: 'algum erro no comentário/spot' }
        elsif new_spot && @spot.save
          unless @comment.design.user.id == @comment.user.id
            CommentMailer.new_comment(@comment).deliver_now
          end
          format.js { render template: 'comments/brand_new' and return }
          format.html { redirect_to root_path, notice: 'comentário criado com sucesso' }
        elsif exist_spot && @spot.save
          unless @comment.design.user.id == @comment.user.id
            CommentMailer.new_comment(@comment).deliver_now
          end
          format.js { render template: 'comments/existing' and return }
          format.html { redirect_to root_path, notice: 'comentário criado com sucesso' }
        else
          format.js { head :unprocessable_entity and return }
          format.html { redirect_to root_path, notice: 'algum erro no comentário' }
        end
      end
      # p 'should never get here'
    end

    # Ajax
    # Delete a comment or a spot (and its comments)
    def delete
      spot_destroyed = false
      if Comment.exists?(params[:comment_id])
        @comment = Comment.find(params[:comment_id])
        @spot = @comment.spot
        # verify if this is the last/unique comment remaining
        # if yes, then need to delete the spot too
        if @spot.comments.count <= 1
          @spot.destroy
          spot_destroyed = true
        else
          @comment.destroy
        end
      end

      respond_to do |format|
        if spot_destroyed
          format.js { render template: 'comments/spot_delete' and return }
          format.html { redirect_to :back }
        else
          format.js { render template: 'comments/comment_delete' and return }
          format.html { redirect_to :back }
        end
      end
    end

    private

      # just the design/comment owner can delete the comment
      def allowed_user
        redirect_to root_url and return if !user_signed_in? || params[:comment_id].blank?

        if Comment.exists?(params[:comment_id])
          comment = Comment.find(params[:comment_id])
          comment_owner = current_user.comments.exists?(comment.id)
          design_owner =  current_user.designs.exists?(comment.design.id)
          unless comment_owner || design_owner
            p "be careful, user isn\'t design/comment owner and is trying to delete the comment -> user_id: #{current_user.id}"
            redirect_to root_url
          end
        else
          redirect_to root_url
        end
      end

end

app/helpers/admin/comments_helper.rb
module Admin::CommentsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/admin/comments/edit.html.erb
<div class="row">
  <div class="small-12 columns">
    <% if @comment.errors.any? %>
      <% @comment.errors.full_messages.each do |error| %>
        <p><%= error %></p>
      <% end %>
    <% end%>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">

    <%= form_for [:admin, @comment] do |f| %>

      <div>
        <%= f.label :comment %>
        <%= f.text_field :comment %>
      </div>

      <div>
        <%= f.submit 'Atualizar', class: 'bt' %>
      </div>

    <% end %>

  </div>
</div>

app/views/admin/comments/index.html.erb
<div class="row">
  <div class="small-12 columns">
    <% # link_to 'Criar Usuário', new_admin_user_path %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">

    <% if @comments.any? %>
      <table>
        <thead>
          <tr>
            <th>Actions</th>
            <th>ID</th>
            <th>Comment</th>
            <th>belongs to - Name</th>
            <th>belongs to - ID</th>
          </tr>
        </thead>
        <tbody>
          <% @comments.each do |comment| %>
            <tr>
              <td class="df-admin-resource-actions">
                <span class="df-admin-resource-show"><%= link_to admin_comment_path(comment.id) do '<i class="fa fa-eye"></i>'.html_safe end %></span>
                <span class="df-admin-resource-edit"><%= link_to edit_admin_comment_path(comment.id) do '<i class="fa fa-pencil"></i>'.html_safe end %></span>
                <span class="df-admin-resource-delete"><%= link_to admin_comment_path(comment.id), method: :delete, data: {confirm: 'Você tem certeza que deseja apagar esse comentário? Tudo associado a este comentário será apagado.'} do '<i class="fa fa-minus-circle"></i>'.html_safe end %></span>
              </td>
              <td><%= comment.id %></td>
              <td><%= comment.comment %></td>
              <td><%= comment.user.name %></td>
              <td class="text-center"><%= comment.user.id %></td>
            </tr>
          <% end %>
        </tbody>
      </table>

      <%= paginate @comments %>

    <% else %>
      <p>Sem Comentários ainda</p>
    <% end %>

  </div>
</div>

app/views/admin/comments/show.html.erb
<div class="row">
  <div class="small-12 columns">
    <%= link_to 'Edit Comment', edit_admin_comment_path(@comment.id) %>
  </div>
</div>

<div class="row">
  <div class="small-12 columns">
    <table>
      <thead>
        <tr>
          <th>Campo</th>
          <th>Valor</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td>ID</td>
          <td><%= @comment.id %></td>
        </tr>
        <tr>
          <td>Comment</td>
          <td><%= @comment.comment %></td>
        </tr>
        <tr>
          <td>Belongs to - Name</td>
          <td><%= @comment.user.name %></td>
        </tr>
        <tr>
          <td>Belongs to - ID</td>
          <td><%= @comment.user.id %></td>
        </tr>
        <tr>
          <td>Created at</td>
          <td><%= @comment.created_at %></td>
        </tr>
        <tr>
          <td>Updated at</td>
          <td><%= @comment.updated_at %></td>
        </tr>
      </tbody>
    </table>
  </div>
</div>