config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  #override the admin devise controller to ours
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }

  get 'admin', to: 'admin/dashboard#index'

  # namespace all admin resources
  namespace :admin do
    resources :users, :designs, :comments, :spots
  end

  # override the user devise controller to ours
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations'
  }

  get 'projetos', to: 'dynamic_pages#projetos'
  get 'individuais/minhas-imagens', to: 'dynamic_pages#individuais', as: :individuais
  get 'individuais/onde-comentei', to: 'dynamic_pages#my_comments', as: :my_comments
  post 'create_single', to: 'singles#create', as: :create_single

  # resources :users

  match 'contato', to: 'static_pages#contact', via: [:get, :post], as: :contact

  match 'a/create_comment', to: 'comments#create', via: [:post], as: :create_design_comment
  match 'a/delete_comment/:comment_id', to: 'comments#delete', via: [:delete], as: :delete_design_comment
  match 'a/delete_spot/:spot_id', to: 'spots#delete', via: [:delete], as: :delete_design_spot
  match 'delete_design/:design_id', to: 'singles#delete', via: [:delete], as: :delete_design

  match 'a/update_title', to: 'singles#update_title', via: [:patch], as: :update_design_title
  match 'a/update_subtitle', to: 'singles#update_subtitle', via: [:patch], as: :update_design_subtitle
  match 'a/feedback_app', to: 'singles#feedback_app', via: [:get], as: :feedback_app

  match ':design_link', to: 'singles#show', via: [:get], as: :design

end

app/views/shared/_debug_stuff.html.erb
<div class="row">
  <div class="small-12 columns">
    <hr>
    <div><b>Params</b></div>
    <%= debug params %>
    <hr>
    <div><b>Devise Notifications</b></div>
    <%= debug notice %>
    <%= debug alert %>
    <div><b>Flash</b></div>
    <%= debug flash %>
  </div>
</div>

app/views/shared/_design_footer.html.erb
<footer class="max-width df-design-footer">
  <div class="row">
    <div class="small-12 columns">
      <hr>
    </div>
    <div class="small-12 medium-4 columns">
      <p class="df-footer-copyright"><%= Time.now.year %> - Todos os Direitos Reservados</p>
      <nav class="df-footer-navigation invisible">
        <ul>
          <li><a href="">Home</a></li>
          <li><a href="">Como Funciona</a></li>
          <li><a href="">Planos</a></li>
          <li><a href="">Blog</a></li>
        </ul>
      </nav>
    </div>
    <div class="small-12 medium-8 columns">
      <span class="df-design-footer-logo right"><span>Design</span><strong>Feedback</strong></span>
    </div>
  </div>
</footer>

app/views/shared/_design_nav.html.erb
<header class="max-width df-design-main-header">
  <div class="row">
    <!-- Top Nav BEGIN -->
    <div class="small-12 medium-4 columns">
      <%= link_to root_url do %>
        <h1 class="df-main-logo"><span>Design</span><strong>Feedback</strong></h1>
      <% end  %>
    </div>
    <nav class="small-12 medium-8 columns df-design-top-navigation">
      <ul class="right">
        <% if user_signed_in? && current_user.id == @design.user.id %>
          <li><%= link_to 'Painel', individuais_path, {class: 'normal'} %></li>
          <li class="hide"><%= link_to 'Dados Pessoais', edit_user_registration_path, {class: 'normal'} %></li>
          <li class="hide"><%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'normal' %></li>
          <li class="share" data-reveal-id="js-df-modal-link">Compartilhar Link</li>
        <% elsif user_signed_in? %>
          <li><%= link_to 'Painel', individuais_path, {class: 'featured'} %></li>
          <li><%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'normal' %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path, {class: 'normal'} %></li>
          <li><%= link_to 'Cadastre-se Gratuitamente', new_user_registration_path, {class: 'featured'} %></li>
        <% end %>
      </ul>
    </nav>
    <div class="small-12 columns">
      <hr class="df-nav-separator">
    </div>
    <!-- Top Nav END -->
  </div>
</header>

app/views/shared/_feedback_form.html.erb
<div id="feedback-form-app" >
  <%= form_tag( feedback_app_path, method: 'GET', remote: true, authenticity_token: true, class: 'js-form-feedback-form' ) do %>
    <div>

      <%= label_tag :feedback_text do %>
        <%= text_area_tag :feedback_text, '', {required: true, id: 'feedback_user_text', class: 'feedback_user', placeholder: 'Sua Mensagem'} %>
      <% end %>

      <%= submit_tag 'Enviar', class: 'button', data: { disable_with: 'Enviando...' } %>
      <span class="js-single-feedback-refresh hide"><i class="fa fa-refresh fa-spin"></i></span>
      <p id="feedback-post-email-message" class="hide">Email enviado com sucesso.</p>
    </div>
  <% end %>
</div>

app/views/shared/_home_footer.html.erb
<footer class="max-width df-main-footer">
  <div class="row">
    <div class="small-12 medium-4 columns">
      <p class="df-footer-copyright"><%= Time.now.year %> - Todos os Direitos Reservados</p>
      <nav class="df-footer-navigation invisible">
        <ul>
          <li><a href="">Home</a></li>
          <li><a href="">Como Funciona</a></li>
          <li><a href="">Planos</a></li>
          <li><a href="">Blog</a></li>
        </ul>
      </nav>
    </div>
    <div class="small-12 medium-8 columns">
      <span class="df-footer-logo right"><span>Design</span><strong>Feedback</strong></span>
    </div>
  </div>
</footer>

app/views/shared/_home_nav.html.erb
<header class="max-width df-home-main-header">
  <div class="row">
    <!-- Top Nav BEGIN -->
    <div class="small-12 medium-4 columns">
      <%= link_to root_url do %>
        <h1 class="df-main-logo"><span>Design</span><strong>Feedback</strong></h1>
      <% end  %>
    </div>
    <nav class="small-12 medium-8 columns df-home-top-navigation">
      <ul class="right">
        <% if user_signed_in? %>
          <li class="normal">Olá, <%= current_user.name %></li>
          <li><%= link_to 'Painel', individuais_path, {class: 'featured'} %></li>
          <li><%= link_to 'Dados Pessoais', edit_user_registration_path, {class: 'normal'} %></li>
          <li><%= link_to 'Sair', destroy_user_session_path, method: :delete, class: 'normal' %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path, {class: 'normal'} %></li>
          <li><%= link_to 'Cadastre-se Gratuitamente', new_user_registration_path, {class: 'featured'} %></li>
        <% end %>
        <li><%= link_to 'Contato', contact_path, {class: 'normal'} %></li>
      </ul>
    </nav>
    <!-- Top Nav END -->
  </div>
</header>

app/views/shared/_notifications.html.erb
<% if notice.present? || alert.present? %>

  <section id="df-notifications" class="df-notifications max-width hide">
    <% if notice %>
      <p id="js-df-devise-notice" class="notice"><%= notice %></p>
    <% end %>

    <% if alert %>
      <p id="js-df-devise-alert" class="alert"><%= alert %></p>
    <% end %>

  </section>

<% end %>