config/routes.rb
Rails.application.routes.draw do

  root 'static_pages#home'

  #override the admin devise controller to ours
  devise_for :admins, :controllers => {
    :sessions => 'admins/sessions'
  }

  get 'admin', to: 'admin/dashboard#index'

  # namespace all admin resources
  namespace :admin do
    resources :users, :designs, :comments, :spots
  end

  # override the user devise controller to ours
  devise_for :users, :controllers => {
    :sessions => 'users/sessions',
    :registrations => 'users/registrations',
    :passwords => 'users/passwords',
    :confirmations => 'users/confirmations'
  }

  get 'projetos', to: 'dynamic_pages#projetos'
  get 'individuais/minhas-imagens', to: 'dynamic_pages#individuais', as: :individuais
  get 'individuais/onde-comentei', to: 'dynamic_pages#my_comments', as: :my_comments
  post 'create_single', to: 'singles#create', as: :create_single

  # resources :users

  match 'contato', to: 'static_pages#contact', via: [:get, :post], as: :contact

  match 'a/create_comment', to: 'comments#create', via: [:post], as: :create_design_comment
  match 'a/delete_comment/:comment_id', to: 'comments#delete', via: [:delete], as: :delete_design_comment
  match 'a/delete_spot/:spot_id', to: 'spots#delete', via: [:delete], as: :delete_design_spot
  match 'delete_design/:design_id', to: 'singles#delete', via: [:delete], as: :delete_design

  match 'a/update_title', to: 'singles#update_title', via: [:patch], as: :update_design_title
  match 'a/update_subtitle', to: 'singles#update_subtitle', via: [:patch], as: :update_design_subtitle
  match 'a/feedback_app', to: 'singles#feedback_app', via: [:get], as: :feedback_app

  match ':design_link', to: 'singles#show', via: [:get], as: :design

end

app/controllers/singles_controller.rb
class SinglesController < ApplicationController
  before_action :authenticate_user!, only: [:create, :update_title, :update_subtitle, :delete]
  before_action :allowed_user, only: [:update_title, :update_subtitle, :delete]

  # Ajax
  # Create Designs based on user image uploads, creating images, thumbs, filenames
  # Params (through rails params):
  # +design_images+:: <ActionController::Parameters>
  # Returns
  # @design <Design> with the design created
  # @images_added <Array> containing all the images created through params[:design_images]
  def create

    require 'RMagick'
    @images_added = []

    # params[:design_images] is set by a js library (Dropzone.js) and defined on dynamic_pages.js paramName
    params[:design_images].each do |array_file|

      # uploaded file example
      # {"0"=>#<ActionDispatch::Http::UploadedFile:0x007f88cf70b728 @tempfile=#<Tempfile:/var/folders/tx/fcpjq87x6b19sl3dvvm8fr040000gn/T/RackMultipart20150803-99318-18nmoiu.jpg>, @original_filename="10881656_10201963394846606_706439852029346946_n.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"singular_design[0]\"; filename=\"10881656_10201963394846606_706439852029346946_n.jpg\"\r\nContent-Type: image/jpeg\r\n">, "1"=>#<ActionDispatch::Http::UploadedFile:0x007f88cf70b610 @tempfile=#<Tempfile:/var/folders/tx/fcpjq87x6b19sl3dvvm8fr040000gn/T/RackMultipart20150803-99318-1loctd5.jpg>, @original_filename="11062261_825163280904553_6934851262428256525_n.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"singular_design[1]\"; filename=\"11062261_825163280904553_6934851262428256525_n.jpg\"\r\nContent-Type: image/jpeg\r\n">}

      uploaded_file = array_file.last

      # file checking (size and filetype)
      return false if !valid_img? uploaded_file

      # main image random filename
      random_filename = build_filename(uploaded_file)

      image = Magick::Image.from_blob(uploaded_file.read).first
      original_width = image.columns # columns are pixels
      original_height = image.rows # rows are pixels

      # just resize if image is larger in width
      image = image.resize_to_fit(2000, original_height) if original_width >= 2000
      image.write(Rails.root.join('public', 'assets', 'uploads','designs', random_filename))

      # thumbnail image random filename
      thumb_random_filename = build_filename(uploaded_file, true)
      thumbnail = image.resize_to_fill(250, 150)
      thumbnail.write(Rails.root.join('public', 'assets', 'uploads','designs', thumb_random_filename))

      # generating link for this new design
      random_link = SecureRandom.hex(4)

      while Design.exists?(link: random_link) == true do random_link = SecureRandom.hex(4) end

      @design = Design.new(user_id: current_user.id,
                           link: random_link,
                           image_path: random_filename,
                           image_thumb_path: thumb_random_filename)

      @images_added << @design if @design.save
    end

    respond_to do |format|
      format.html { redirect_to :individuais }
      format.json { render json: @images_added }
    end
  end

  # the main action where the magic occurs :)
  # Params (through rails params):
  # +design_link+:: <ActionController::Parameters>
  # Returns
  # @design <Design>
  def show

    @design = Design.find_by(link: params[:design_link])

    unless @design
      flash[:notice] = 'Nenhum design foi encontrado.'
      redirect_to root_url and return
    end

    if user_signed_in?
      @spots = @design.spots
    else
      session['design_id_before_register'] = @design.id
      session['design_username_before_register'] = @design.user.name
      redirect_to new_user_registration_path and return
    end
  end

  # AJAX
  # action triggered by registered users where they can send messages to admin (tips, problems, request and so on)
  def feedback_app
    @feedback_text = params[:feedback_text]
    respond_to do |format|
      FeedbackMailer.to_admin(@feedback_text, current_user).deliver_now
      format.js { render template: 'singles/feedback_app.js.erb' }
    end
  end

  # the delete action to remove the single
  def delete
    @design = Design.find(params[:design_id])
    @design.destroy
    flash[:notice] = 'Imagem deletada com sucesso'
    redirect_to individuais_path
  end

  # AJAX
  # name says it all. token is being sent by the request object (not by the form) jquery-rails take care of it (csrf in  <head>)
  def update_title
    return if params[:design_id].nil?

    @design = Design.find(params[:design_id])
    @design.title = params[:design_title]

    respond_to do |format|
      if @design.save
        format.html { redirect_to :back }
        format.js { render template: 'singles/update_title.js.erb' }
      else
        format.html { redirect_to root_path, notice: 'Erro ao atualizar o titulo do design.' }
      end
    end
  end

  # AJAX
  # name says it all. token is being sent by the request object (not by the form) jquery-rails take care of it (csrf in  <head>)
  def update_subtitle
    return if params[:design_id].nil?

    @design = Design.find(params[:design_id])
    @design.subtitle = params[:design_subtitle]

    respond_to do |format|
      if @design.save
        format.html { redirect_to :back }
        format.js { render template: 'singles/update_subtitle.js.erb' }
      else
        format.html { redirect_to root_path, notice: 'Erro ao atualizar o subtítulo do design' }
      end
    end
  end

  private

    # Create a random filename based on file, thumb and current_user.id
    # Params:
    # +file+:: <ActionDispatch::Http::UploadedFile>
    # +thumb+:: <Boolean>
    # Returns
    # <String> containing the full filename: ex. image-1.png, mythumb-thumb-2.jpg
    def build_filename(file, thumb = false)
      if thumb
        new_filename = SecureRandom.hex(8).to_s + '-thumb-' + current_user.id.to_s
      else
        new_filename = SecureRandom.hex(8).to_s + '-' + current_user.id.to_s
      end

      extension = if (file.content_type == 'image/png')
                    '.png'
                  elsif (file.content_type == 'image/jpeg')
                    '.jpeg'
                  elsif (file.content_type == 'image/jpg')
                    '.jpg'
                  end
      return new_filename + extension
    end

    # Check if the user is allowed and redirect to root_url if not
    def allowed_user
      unless current_user.id == Design.find(params[:design_id]).user.id
        flash[:notice] = 'Voce não tem permissão para fazer isso!'
        redirect_to root_url
      end
    end

    # Check image validity based on file size and type
    # Params:
    # +file+:: <ActionDispatch::Http::UploadedFile>
    # Returns
    # <Boolean> true if everything went well
    # <StandardError> if it fails
    def valid_img?(file = nil)
      return nil if file.nil?

      # checking file size
      if file.size > 25000000
        p "#{uploaded_file.last.size} bigger than 25MB"
        raise StandardError, 'Uploaded File Size Exceeded'
      end

      # checking file type
      unless file.content_type == 'image/jpeg' || file.content_type == 'image/jpg' || file.content_type == 'image/png'
        raise StandardError, 'Not Permitted Filetype'
      end

      return true
    end

end

app/helpers/singles_helper.rb
module SinglesHelper
end

app/views/singles/feedback_app.js.erb
(function() {  
  $('.js-single-feedback-refresh').addClass('hide');
  $('#feedback-post-email-message').removeClass('hide');
  $('#feedback_user_text').val('');

  setTimeout(function(){
    $('#js-df-modal-feedback').foundation('reveal', 'close');
    $('#feedback-post-email-message').addClass('hide');
  }, 2000);
}());

app/views/singles/show.html.erb
<div id="df-design-page" class="design-single-container">

  <section class="row">
    <div class="small-12 medium-6 columns df-design-single-meta-container">
      <div class="row">

        <% if user_signed_in? && current_user.id == @design.user.id %>
          <div class="small-12 columns df-single-inputs-container">
            <%= form_tag(update_design_title_path, method: 'PATCH', remote: true, authenticity_token: true, class: 'js-form-update-title' ) do %>
              <%= text_field_tag :design_id, @design.id, {type: 'hidden'} %>
              <div class="df-input-stacked">
                <%= text_field_tag :design_title, @design.title, {id: 'new_design_title', class: 'new_design_title_single', placeholder: 'Insira um título' } %>
                <i class="fa js-form-update-icon"></i>
              </div>
            <% end %>
          </div>

          <div class="small-12 columns df-single-inputs-container">
            <%= form_tag(update_design_subtitle_path, method: 'PATCH', remote: true, authenticity_token: true, class: 'js-form-update-subtitle' ) do %>
              <%= text_field_tag :design_id, @design.id, {type: 'hidden'} %>
              <div class="df-input-stacked">
                <%= text_field_tag :design_subtitle, @design.subtitle, {id: 'new_design_subtitle', class: 'new_design_subtitle_single', placeholder: 'Breve Descrição' } %>
                <i class="fa js-form-update-icon"></i>
              </div>
            <% end %>
          </div>

        <% else %>

          <div class="small-12 columns">
            <p class="df-single-meta-title"><span class="hide">Titulo: </span><%= @design.title %></p>
            <p class="df-single-meta-subtitle"><span class="hide">Subtítulo: </span><%= @design.subtitle %></p>
          </div>

        <% end %>
      </div>
    </div>

    <div class="small-12 medium-6 columns df-single-date-container">
      <% if user_signed_in? && current_user.id == @design.user.id %>
        <%= link_to "Deletar Imagem", delete_design_path(@design.id), method: :delete, class: 'df-single-delete-design', data: { confirm: 'Voce tem certeza que deseja apagar esse design?' } %>
      <% end %>
      <p class="df-single-date">criado: <%= l @design.created_at, :format => '%d/%m/%Y' %></p>
    </div>

    <div class="small-12 columns">
      <p class="df-design-single-click-around">Clique em qualquer área da imagem e fique livre para dar um feedback!</p>
    </div>

  </section>

  <main class="row js-main-app">
    <div class="small-12 columns">
      <div class="js-design-container">

        <%= image_tag design_fs_path + @design.image_path, {id: 'js-design-img'} %>
        <div class="js-spots-container">
          <% if @spots.any? %>
            <% @spots.each do |spot| %>
              <div class="spot-comment-container">
                <span data-spot-id="<%= spot.id %>" class="js-design-spot" style="top: <%= spot.y_pos.to_i - 10 %>px; left: <%= spot.x_pos.to_i - 10 %>px"></span>
                <div data-spot-ref="<%= spot.id %>" class="js-existing-spot-form js-spot-form" style="top: <%= spot.y_pos %>px; left: <%= spot.x_pos %>px">
                  <%= form_tag(create_design_comment_path, {remote: true}) do %>

                    <% if spot.comments.any? %>
                      <div class="comments-container">
                        <% spot.comments.each_with_index do |comment, index| %>
                          <p class="design-comment" data-comment-id="<%= comment.id %>">
                            <%= comment.comment %> <span data-user-ref="<%= comment.user.id %>" class="js-username-comment">- <%= comment.user.name %></span>
                            <% if index == 0 %>
                              <% if comment.can_user_delete?(current_user) %>
                                <%= link_to delete_design_spot_path(spot.id), remote: true, method: :delete, class: 'design-comment-delete', data: {confirm: 'Atenção: todos os comentários pertencentes a este feedback serão apagados. Tem certeza?'}  do %>
                                  <i class="fa fa-trash"></i>
                                <% end %>
                              <% end %>
                            <% else %>
                              <% if comment.can_user_delete?(current_user) %>
                                <%= link_to delete_design_comment_path(comment.id), remote: true, method: :delete, class: 'design-comment-delete', data: {confirm: 'Você tem certeza que deseja apagar esse comentário?'} do %>
                                <i class="fa fa-trash"></i>
                                <% end %>
                              <% end %>
                            <% end %>
                          </p>
                        <% end %>
                      </div>
                    <% else %>
                      <p>este spot deve ser apagado, não pode existir spots sem comentários</p>
                    <% end %>

                    <%= text_field_tag 'design-id', @design.id, { type: 'hidden'} %>
                    <%= text_field_tag 'spot-id', spot.id, { type: 'hidden'} %>
                    <%= text_area_tag  'design-comment-text', nil,  {class: 'js-maintain-focus js-design-comment-text'} %>
                    <%= button_tag 'Enviar Feedback', class: 'design-comment-submit', data: { disable_with: 'Enviando...'} %>

                  <% end %>
                </div><!-- end .jd-spot-form -->
              </div><!-- end .spot-comment-container -->

            <% end %>
          <% end  %>
        </div>

        <div class="js-new-spot-comment-container">
          <span class="js-design-spot js-new-design-spot hide"></span>
          <div class="js-add-new-spot js-spot-form">
            <%= form_tag(create_design_comment_path, {remote: true} ) do %>
              <p class="design-new-feedback-title">Deixe seu Feedback</p>
              <%= text_field_tag 'design-id', @design.id, {type: 'hidden'} %>
              <%= text_field_tag 'design-x-pos', false, { type: 'hidden'} %>
              <%= text_field_tag 'design-y-pos', false, { type: 'hidden'} %>
              <%= text_area_tag  'design-comment-text', nil, { class: 'js-maintain-focus js-design-comment-text'} %>
              <%= button_tag 'Enviar Feedback', class: 'design-comment-submit', data: { disable_with: 'Enviando...'} %>
            <% end %>
          </div>
        </div>

      </div><!-- end .js-design-container -->
    </div>

  </main>

  <section>

    <div id="js-df-modal-link" class="reveal-modal medium df-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
      <p class="lead">Link de Compartilhamento</p>
      <p>Envie este link para quem você quiser compartilhar esta imagem.</p>
      <p id="df-modal-link">http://designfeedback.com.br/<%= @design.link %></p><br>
      <button id="df-copy-to-clipboard-link" type="button" title="Clique para copiar o link deste design" data-clipboard-text="http://designfeedback.com.br/<%= @design.link %>">Clique aqui para copiar o link</button>
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>

    <div class="df-feedback-form-container hide">
      <p>Achou algum erro?</p>
      <p>Gostaria de algo a mais?</p>
      <button data-reveal-id="js-df-modal-feedback" name="button">Clique aqui</button>
    </div>

    <div id="js-df-modal-feedback" class="df-modal-single-feedback reveal-modal medium df-modal" data-reveal aria-labelledby="modalTitle" aria-hidden="true" role="dialog">
      <p class="lead">Olá</p>
      <p>Achou algum erro?</p>
      <p>Gostaria de algo que não existe na nossa ferramenta?</p>
      <p>Nos conte!</p>
      <%= render 'shared/feedback_form' %>
      <a class="close-reveal-modal" aria-label="Close">&#215;</a>
    </div>

  </section>
</div>

app/views/singles/update_subtitle.js.erb
(function() {
  $('#new_design_subtitle').val("<%= @design.subtitle %>");
}());

app/views/singles/update_title.js.erb
(function() {  
  $('#new_design_title').val("<%= @design.title %>");
}());